// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Array: typeof import('./src/components/defaults/array.vue')['default']
    Checkbox: typeof import('./src/components/defaults/checkbox.vue')['default']
    FormArray: typeof import('./src/components/FormArray.vue')['default']
    FormItem: typeof import('./src/components/FormItem.vue')['default']
    Input: typeof import('./src/components/defaults/input.vue')['default']
    JsonSchema: typeof import('./src/components/JsonSchema.vue')['default']
    Radio: typeof import('./src/components/defaults/radio.vue')['default']
    Select: typeof import('./src/components/defaults/select.vue')['default']
    Wrapper: typeof import('./src/components/defaults/wrapper.vue')['default']
  }
}
